install: 
 - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - echo "deb http://download.mono-project.com/repo/debian nightly main" | sudo tee /etc/apt/sources.list.d/mono-xamarin-nightly.list
 - sudo apt-get update
 - sudo apt-get install mono-devel
script:
 - ./build.sh
